In [ ]:
import pandas as pd
energy = pd.DataFrame(pd.read_excel("/Users/igor/Documents/GitHub/Camp2025/lesson3/Energy Indicators.xls"))

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,NaN,NaN,Environmental Indicators: Energy,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Energy Supply and Renewable Electricity Produc...,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,Last update: December 2015
...,...,...,...,...,...,...
277,NaN,… denotes no data available.,NaN,NaN,NaN,NaN
278,NaN,NaN,NaN,NaN,NaN,NaN
279,NaN,Data Quality:,NaN,NaN,NaN,NaN
280,NaN,The data are compiled primarily from the annua...,NaN,NaN,NaN,NaN
281,NaN,"For more information, visit http://unstats.un....",NaN,NaN,NaN,NaN