In [244]:
import pandas as pd
import numpy as np

def answer_one():
    data = pd.read_excel("Energy Indicators.xls", skiprows = 17, usecols = "C,D,E,F", skipfooter = 38, names=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable'])
    energy = pd.DataFrame(data)
    energy.replace("...", np.nan, inplace=True)
    energy['Energy Supply'] = energy['Energy Supply']*1000000
    energy['Country'] = energy['Country'].str.replace(r'\d{1,2}$', '', regex = True).str.strip()
    energy['Country'] = energy['Country'].str.replace(r'\(.*\)', '', regex = True).str.strip()
    value_for_replacing = ["Republic of Korea", "United States of America", "United Kingdom of Great Britain and Northern Ireland", 'China, Hong Kong Special Administrative Region']
    required_values = ["South Korea", "United States", "United Kingdom", "Hong Kong"]
    energy.replace(value_for_replacing, required_values, inplace=True)
    gdp_data = pd.read_csv("world_bank.csv", sep=',', skiprows=4)
    GDP = pd.DataFrame(gdp_data)
    value_to_replace = ['Korea, Rep.','Iran, Islamic Rep.','Hong Kong SAR, China']
    replacement_value = ['South Korea','Iran','Hong Kong']
    GDP.replace(value_to_replace, replacement_value, inplace = True)
    ScimEn_data = pd.read_excel("scimagojr country rank 1996-2023.xlsx")
    ScimEn = pd.DataFrame(ScimEn_data)
    df = pd.merge(energy,ScimEn,how = 'inner', left_on='Country', right_on='Country')
    df = pd.merge(df,GDP,how = 'inner', left_on='Country', right_on='Country Name')
    df = df[df['Rank']<=15]
    df = df[['Country','Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']]
    return df

answer_one()

/var/folders/xr/v5m61tlj65x51xn5n3hz1ll40000gn/T/ipykernel_15115/934717352.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  energy.replace("...", np.nan, inplace=True)

,Country,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,Energy Supply,Energy Supply per Capita,...,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015
9,Australia,14,27993,27254,608021,84747,21.72,234,5.386000e+09,231.0,...,7.479074e+11,8.544273e+11,1.055686e+12,9.286298e+11,1.148570e+12,1.398456e+12,1.546953e+12,1.576330e+12,1.467590e+12,1.350580e+12
24,Brazil,15,27316,26888,307607,71778,11.26,154,1.214900e+10,59.0,...,1.107627e+12,1.397114e+12,1.695855e+12,1.666996e+12,2.208838e+12,2.616157e+12,2.465228e+12,2.472819e+12,2.456044e+12,1.802212e+12
31,Canada,8,41209,40390,915491,142691,22.22,284,1.043100e+10,296.0,...,1.319265e+12,1.468820e+12,1.552990e+12,1.374625e+12,1.617343e+12,1.793327e+12,1.828366e+12,1.846597e+12,1.805750e+12,1.556509e+12
36,China,1,402188,400158,5077232,3511673,12.62,343,1.271910e+11,93.0,...,2.752119e+12,3.550328e+12,4.594337e+12,5.101691e+12,6.087192e+12,7.551545e+12,8.532186e+12,9.570471e+12,1.047562e+13,1.106157e+13
55,France,12,30810,30139,547122,89958,17.76,221,1.059700e+10,166.0,...,2.320536e+12,2.660591e+12,2.930304e+12,2.700887e+12,2.645188e+12,2.865158e+12,2.683672e+12,2.811877e+12,2.855964e+12,2.439189e+12
59,Germany,6,50906,49773,777362,160302,15.27,252,1.326100e+10,165.0,...,2.994704e+12,3.425578e+12,3.745264e+12,3.411261e+12,3.399668e+12,3.749315e+12,3.527143e+12,3.733805e+12,3.889093e+12,3.357586e+12
73,India,3,81853,79757,968523,369256,11.83,237,3.319500e+10,26.0,...,9.402599e+11,1.216736e+12,1.198895e+12,1.341888e+12,1.675616e+12,1.823052e+12,1.827638e+12,1.856721e+12,2.039126e+12,2.103588e+12
75,Iran,11,32080,31725,634135,177894,19.77,198,9.172000e+09,119.0,...,2.662989e+11,3.498816e+11,4.123362e+11,4.163970e+11,4.868076e+11,6.261331e+11,6.440355e+11,4.927756e+11,4.603828e+11,4.082129e+11
79,Italy,9,38700,36909,639473,147302,16.52,209,6.530000e+09,109.0,...,1.949552e+12,2.213102e+12,2.408655e+12,2.199929e+12,2.136100e+12,2.294994e+12,2.086958e+12,2.141924e+12,2.162010e+12,1.836638e+12
81,Japan,4,58342,57735,717946,154848,12.31,228,1.898400e+10,149.0,...,4.601663e+12,4.579750e+12,5.106679e+12,5.289494e+12,5.759072e+12,6.233147e+12,6.272363e+12,5.212328e+12,4.896994e+12,4.444931e+12
132,South Korea,10,38362,38046,618762,105419,16.13,198,1.100700e+10,221.0,...,1.053217e+12,1.172614e+12,1.047339e+12,9.439419e+11,1.144067e+12,1.253223e+12,1.278428e+12,1.370795e+12,1.484318e+12,1.465773e+12
134,Russian Federation,7,46186,45868,217996,96688,4.72,112,3.070900e+10,214.0,...,9.899321e+11,1.299703e+12,1.660848e+12,1.222646e+12,1.524917e+12,2.045923e+12,2.208294e+12,2.292470e+12,2.059242e+12,1.363482e+12
148,Spain,13,29840,29156,614087,104845,20.58,216,4.923000e+09,106.0,...,1.260399e+12,1.474003e+12,1.631863e+12,1.491473e+12,1.422108e+12,1.480710e+12,1.324751e+12,1.355580e+12,1.371821e+12,1.196157e+12
166,United Kingdom,5,56288,54713,1095371,179764,19.46,293,7.920000e+09,124.0,...,2.709978e+12,3.092996e+12,2.931684e+12,2.417566e+12,2.491397e+12,2.666403e+12,2.706341e+12,2.786315e+12,3.065223e+12,2.934858e+12
167,United States,2,208042,203356,3540288,1004877,17.02,458,9.083800e+10,286.0,...,1.381559e+13,1.447423e+13,1.476986e+13,1.447806e+13,1.504896e+13,1.559973e+13,1.625397e+13,1.684319e+13,1.755068e+13,1.820602e+13

In [40]:
def answer_two():
    Top15 = answer_one()
    Top15.sort_values("Rank", inplace=True)
    list = Top15.iloc[:, 11:22]
    list_avg = [0for _ in range(15)]
    for i in range(len(list.values.tolist())):
        for j in list.values.tolist()[i]:
            list_avg[i]+=j
        list_avg[i]/=10
    list = Top15["Country"].to_list()
    avgGDP = pd.Series(data=list_avg, index=list).sort_values(ascending=False)
    return avgGDP
answer_two()

/var/folders/xr/v5m61tlj65x51xn5n3hz1ll40000gn/T/ipykernel_15115/934717352.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  energy.replace("...", np.nan, inplace=True)

United States         1.570403e+13
China                 6.927707e+12
Japan                 5.239642e+12
Germany               3.523342e+12
United Kingdom        2.780276e+12
France                2.691337e+12
Italy                 2.142986e+12
Brazil                1.988889e+12
Russian Federation    1.666746e+12
Canada                1.616359e+12
India                 1.602352e+12
Spain                 1.400886e+12
South Korea           1.221372e+12
Australia             1.207513e+12
Iran                  4.563261e+11
dtype: float64

In [226]:
def answer_three():
    country_name = answer_two().index[6]
    country_data = answer_one().set_index("Country").loc[country_name]
    return int(country_data["2006"]-country_data["2015"])
answer_three()

/var/folders/xr/v5m61tlj65x51xn5n3hz1ll40000gn/T/ipykernel_15115/934717352.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  energy.replace("...", np.nan, inplace=True)
/var/folders/xr/v5m61tlj65x51xn5n3hz1ll40000gn/T/ipykernel_15115/934717352.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  energy.replace("...", np.nan, inplace=True)

112914008329

In [225]:
def answer_four():
    Top15 = pd.DataFrame()
    Top15 = answer_one()[['Country', 'Citations', 'Self-citations']].copy()
    Top15.insert(3, "Ratio", np.nan)
    Top15['Ratio']=Top15['Self-citations']/Top15['Citations']
    Top15 = Top15.sort_values(ascending=False, by='Ratio')
    tuple = (Top15['Country'].iloc[0], float(Top15['Ratio'].iloc[0]))
    return tuple
answer_four()

/var/folders/xr/v5m61tlj65x51xn5n3hz1ll40000gn/T/ipykernel_15115/934717352.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  energy.replace("...", np.nan, inplace=True)

('China', 0.6916510807463594)

In [224]:
def answer_five():
    Top15 = answer_one()
    Top15['Estimation'] = Top15['Energy Supply']/Top15['Energy Supply per Capita']
    Top15 = Top15.sort_values(by='Estimation', ascending=False)
    result = Top15.iloc[2]['Country']
    return result
answer_five()

/var/folders/xr/v5m61tlj65x51xn5n3hz1ll40000gn/T/ipykernel_15115/934717352.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  energy.replace("...", np.nan, inplace=True)

'United States'

In [228]:
def answer_six():
    Top15 = answer_one()
    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    Top15['Citable per capita'] = Top15['Citable documents'] / Top15['Population']
    return float(Top15['Citable per capita'].corr(Top15['Energy Supply per Capita'], method='pearson'))
answer_six()

/var/folders/xr/v5m61tlj65x51xn5n3hz1ll40000gn/T/ipykernel_15115/934717352.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  energy.replace("...", np.nan, inplace=True)

0.7019601723071185

In [257]:
import pandas as pd

def answer_seven():
    Top15 = answer_one()  # Переконайтеся, що ця функція повертає DataFrame зі стовпцем 'Country'
    
    ContinentDict = {
        'China': 'Asia', 
        'United States': 'North America', 
        'Japan': 'Asia', 
        'United Kingdom': 'Europe', 
        'Russian Federation': 'Europe', 
        'Canada': 'North America', 
        'Germany': 'Europe', 
        'India': 'Asia',
        'France': 'Europe', 
        'South Korea': 'Asia', 
        'Italy': 'Europe', 
        'Spain': 'Europe', 
        'Iran': 'Asia',
        'Australia': 'Australia', 
        'Brazil': 'South America'
    }

    if 'Country' in Top15.columns:
        Top15.set_index('Country', inplace=True)
    Top15['Continent'] = Top15.index.map(ContinentDict)
    Top15.dropna(subset=['Continent'], inplace=True)
    Top15['Population'] = Top15['Energy Supply'] / Top15['Energy Supply per Capita']
    result = Top15.groupby('Continent')['Population'].agg(['size', 'sum', 'mean', 'std'])
    return result

answer_seven()

/var/folders/xr/v5m61tlj65x51xn5n3hz1ll40000gn/T/ipykernel_15115/934717352.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  energy.replace("...", np.nan, inplace=True)

               size           sum          mean           std
Continent
Asia              5  2.898666e+09  5.797333e+08  6.790979e+08
Australia         1  2.331602e+07  2.331602e+07           NaN
Europe            6  4.579297e+08  7.632161e+07  3.464767e+07
North America     2  3.528552e+08  1.764276e+08  1.996696e+08
South America     1  2.059153e+08  2.059153e+08           NaN